export const data = [
    {"nombre": "Padres Forzosos","cancion": "pDrsFrZsLkLkOiYu.mp3","imagen": "padres_forzosos.jpg","tipo": "serie"},
    {"nombre": "Sherlock Holmes","cancion": "sHrLckHlMsLkLkOi.mp3","imagen": "sherlock_holmes.jpg","tipo": "dibujos"},
    {"nombre": "Alvin y las Ardillas","cancion": "aYlSvXnZmWlKjH.mp3","imagen": "alvin_y_las_ardillas.jpg","tipo": "dibujos"},
    {"nombre": "Fraggle Rock","cancion": "fRgGlLcKlKjHgFd.mp3","imagen": "fraggle_rock.jpg","tipo": "dibujos"},
    {"nombre": "Los Problemas Crecen","cancion": "lPrBlMsCrSnLkLk.mp3","imagen": "los_problemas_crecen.jpg","tipo": "serie"},
    {"nombre": "Alf","cancion": "aLfGhJkLpOiYuTr.mp3","imagen": "alf.jpg","tipo": "serie"},
    {"nombre": "Aquellos Maravillosos Años","cancion": "aMvRwLsYzXcVbNm.mp3","imagen": "aquellos_maravillosos_anos.jpg","tipo": "serie"},
    {"nombre": "Dragones y Mazmorras","cancion": "dRgNsYmZmRrSvXn.mp3","imagen": "dragones_y_mazmorras.jpg","tipo": "dibujos"},
    {"nombre": "El Inspector Gadget","cancion": "lNsPtRgDgTlKjH.mp3","imagen": "el_inspector_gadget.jpg","tipo": "dibujos"},
    {"nombre": "Friends","cancion": "fRnDsLkLkOiYuTr.mp3","imagen": "friends.jpg","tipo": "serie"},
    {"nombre": "Los Diminutos","cancion": "lDmNtLkLkOiYuTr.mp3","imagen": "los_diminutos.jpg","tipo": "dibujos"},
    {"nombre": "Los Aurones","cancion": "lSdChRlKjHgFdRt.mp3","imagen": "los_aurones.jpg","tipo": "dibujos"},
    {"nombre": "Campeones","cancion": "cMpNlKjHgFdRtYx.mp3","imagen": "campeones.jpg","tipo": "dibujos"},
    {"nombre": "Mofli el Ultimo Koala","cancion": "mFlElLtmKlLkLk.mp3","imagen": "mofli_el_ultimo_koala.jpg","tipo": "dibujos"},
    {"nombre": "Dartacan y los Tres Mosqueperros","cancion": "dRtCnYlTrSsMqS.mp3","imagen": "dartacan_y_los_tres_mosqueperros.jpg","tipo": "dibujos"},
    {"nombre": "Bola de Dragon","cancion": "bDlGhJkLpOiYu.mp3","imagen": "bola_de_dragon.jpg","tipo": "dibujos"},
    {"nombre": "Chip y Chop","cancion": "cYpChPbOlKjHgFd.mp3","imagen": "chip_y_chop.jpg","tipo": "dibujos"},
    {"nombre": "Los Trotamusicos","cancion": "lTrTmSksLkLkOiYu.mp3","imagen": "los_trotamusicos.jpg","tipo": "dibujos"},
    {"nombre": "Buffy Cazavampiros","cancion": "bCzVmPrSvXnZm.mp3","imagen": "buffy_cazavampiros.jpg","tipo": "serie"},
    {"nombre": "Benny Hill","cancion": "bNnYhLlKjHgFdR.mp3","imagen": "benny_hill.jpg","tipo": "serie"},
    {"nombre": "Calimero","cancion": "cLmRvXnZmWlKjHg.mp3","imagen": "calimero.jpg","tipo": "dibujos"},
    {"nombre": "Chicho Terremoto","cancion": "cTrRmTlKjHgFdR.mp3","imagen": "chicho_terremoto.jpg","tipo": "dibujos"},
    {"nombre": "Comando G","cancion": "cMmNdGhJkLpOiY.mp3","imagen": "comando_g.jpg","tipo": "dibujos"},
    {"nombre": "Cosas de Casa","cancion": "cSsDcSvXnZmWlKjH.mp3","imagen": "cosas_de_casa.jpg","tipo": "serie"},
    {"nombre": "Barrio Sesamo","cancion": "bRrStMnSvXnZm.mp3","imagen": "barrio_sesamo.jpg","tipo": "dibujos"},
    {"nombre": "David el Gnomo","cancion": "dVdElGnMmWlKjHg.mp3","imagen": "david_el_gnomo.jpg","tipo": "dibujos"},
    {"nombre": "Dinosaurios","cancion": "dNsRvXnZmWlKjHg.mp3","imagen": "dinosaurios.jpg","tipo": "dibujos"},
    {"nombre": "Doctor en Alaska","cancion": "dCtRnLsKlSkLvXn.mp3","imagen": "doctor_en_alaska.jpg","tipo": "serie"},
    {"nombre": "Sensación de Vivir","cancion": "sNsCnDvVlKjHgFd.mp3","imagen": "sensacion_de_vivir.jpg","tipo": "serie"},
    {"nombre": "Los Ángeles de Charlie","cancion": "lNglDlSdChRlKjH.mp3","imagen": "los_angeles_de_charlie.jpg","tipo": "serie"},
    {"nombre": "Los Caballeros del Zodiaco","cancion": "lCblLlRsdlZdC.mp3","imagen": "los_caballeros_del_zodiaco.jpg","tipo": "dibujos"},
    {"nombre": "El Pájaro Loco","cancion": "lPjRlKjHgFdRtY.mp3","imagen": "el_pajaro_loco.jpg","tipo": "dibujos"},
    {"nombre": "Corrupción en Miami","cancion": "cRpNnMmLvXnZmW.mp3","imagen": "corrupcion_en_miami.jpg","tipo": "serie"},
    {"nombre": "Don Gato y su Pandilla","cancion": "dNtNdSpPnDlLsK.mp3","imagen": "don_gato_y_su_pandilla.jpg","tipo": "dibujos"},
    {"nombre": "Verano Azul","cancion": "vRnZlKjHgFdRtYx.mp3","imagen": "verano_azul.jpg","tipo": "serie"},
    {"nombre": "Bonanza","cancion": "bNnZmWlKjHgFdRt.mp3","imagen": "bonanza.jpg","tipo": "serie"},
    {"nombre": "Érase una vez la vida","cancion": "lVdLsSvXnZmWlKj.mp3","imagen": "erase_una_vez_la_vida.jpg","tipo": "dibujos"},
    {"nombre": "El Bosque de Tallac","cancion": "lBsQfTlLcSvXnZ.mp3","imagen": "el_bosque_de_tallac.jpg","tipo": "dibujos"},
    {"nombre": "El Equipo A","cancion": "lEqApPlKjHgFdRt.mp3","imagen": "el_equipo_a.jpg","tipo": "serie"},
    {"nombre": "Alfred Hitchcock presenta","cancion": "aHpQrEsTlKjHgFd.mp3","imagen": "alfred_hitchcock_presenta.jpg","tipo": "serie"},
    {"nombre": "El Osito Misha","cancion": "lSvXnZmWlKjHgFd.mp3","imagen": "el_osito_misha.jpg","tipo": "dibujos"},
    {"nombre": "El Príncipe Valiente","cancion": "lPrNcVlNtCcSvXn.mp3","imagen": "el_principe_valiente.jpg","tipo": "dibujos"},
    {"nombre": "Embrujada","cancion": "mBrJdLvXnZmWlK.mp3","imagen": "embrujada.jpg","tipo": "serie"},
    {"nombre": "Érase una vez el Hombre","cancion": "rSncLvXnZmWlKjH.mp3","imagen": "erase_una_vez_el_hombre.jpg","tipo": "dibujos"},
    {"nombre": "Expediente X","cancion": "xPdNtXlKjHgFdRtY.mp3","imagen": "expediente_x.jpg","tipo": "serie"},
    {"nombre": "Daniel el Travieso","cancion": "dNlTrVwSvXnZmW.mp3","imagen": "daniel_el_travieso.jpg","tipo": "dibujos"},
    {"nombre": "Batman","cancion": "bTmNlKjHgFdRtYx.mp3","imagen": "batman.jpg","tipo": "dibujos"},
    {"nombre": "Falcon Crest","cancion": "fLcNCrStCcSvXnZ.mp3","imagen": "falcon_crest.jpg","tipo": "serie"},
    {"nombre": "La Tribu de los Brady","cancion": "lTrBdLvXnZmWlKjH.mp3","imagen": "la_tribu_de_los_brady.jpg","tipo": "serie"},
    {"nombre": "Banner y Flapi","cancion": "bYfLaPkOiYuTr.mp3","imagen": "banner_y_flapi.jpg","tipo": "dibujos"},
    {"nombre": "Candy Candy","cancion": "cNdYcNdYlKjHg.mp3","imagen": "candy_candy.jpg","tipo": "dibujos"},
    {"nombre": "Casimiro","cancion": "cSmRvXnZmWlKjHg.mp3","imagen": "casimiro.jpg","tipo": "dibujos"},
    {"nombre": "Fama","cancion": "fMlKjHgFdRtYxPl.mp3","imagen": "fama.jpg","tipo": "serie"},
    {"nombre": "Al Salir de Clase","cancion": "aSdCvBnMlKjHgFdRt.mp3","imagen": "al_salir_de_clase.jpg","tipo": "serie"},
    {"nombre": "Farmacia de Guardia","cancion": "fRmCgRdLvXnZmW.mp3","imagen": "farmacia_de_guardia.jpg","tipo": "serie"},
    {"nombre": "Fútbol en Acción","cancion": "fTbLnCcNnXnZmW.mp3","imagen": "futbol_en_accion.jpg","tipo": "dibujos"},
    {"nombre": "La Llamada de los Gnomos","cancion": "lLlMdDlSgNmsLkL.mp3","imagen": "la_llamada_de_los_gnomos.jpg","tipo": "dibujos"},
    {"nombre": "Gárgolas Héroes Mitológicos","cancion": "gRgLsHrSvXnZmWlK.mp3","imagen": "gargolas_heroes_mitologicos.jpg","tipo": "dibujos"},
    {"nombre": "La vuelta al mundo de Willy Fog","cancion": "lVltLmNdDwLlYfG.mp3","imagen": "la_vuelta_al_mundo_de_willy_fog.jpg","tipo": "dibujos"},
    {"nombre": "Había una vez un Circo","cancion": "hBnCvXnZmWlKjHg.mp3","imagen": "habia_una_vez_un_circo.jpg","tipo": "serie"},
    {"nombre": "Los Halcones Galácticos","cancion": "lHlKnSgLvXnZmW.mp3","imagen": "los_halcones_galacticos.jpg","tipo": "dibujos"},
    {"nombre": "Ferdy","cancion": "fRdYlKjHgFdRtYx.mp3","imagen": "ferdy.jpg","tipo": "dibujos"},
    {"nombre": "Curro Jiménez","cancion": "cJrRmJmNnZmWlKjH.mp3","imagen": "curro_jimenez.jpg","tipo": "serie"},
    {"nombre": "Heidi","cancion": "hDlKjHgFdRtYxPl.mp3","imagen": "heidi.jpg","tipo": "dibujos"},
    {"nombre": "Isidoro","cancion": "iSdRlKjHgFdRtYx.mp3","imagen": "isidoro.jpg","tipo": "dibujos"},
    {"nombre": "Juzgado de Guardia","cancion": "jZgDdGdLvXnZmW.mp3","imagen": "juzgado_de_guardia.jpg","tipo": "serie"},
    {"nombre": "La Abeja Maya","cancion": "lBjMyLkLkOiYuTr.mp3","imagen": "la_abeja_maya.jpg","tipo": "dibujos"},
    {"nombre": "La Aldea del Arce","cancion": "lLdDlRcLvXnZmW.mp3","imagen": "la_aldea_del_arce.jpg","tipo": "dibujos"},
    {"nombre": "Canción Triste de Hill Street","cancion": "cTrStDlHlSvXnZ.mp3","imagen": "cancion_triste_de_hill_street.jpg","tipo": "serie"},
    {"nombre": "Cheers","cancion": "cHrSlKjHgFdRtYx.mp3","imagen": "cheers.jpg","tipo": "serie"},
    {"nombre": "La Bola de Cristal","cancion": "lBlDcRstLlKjHg.mp3","imagen": "la_bola_de_cristal.jpg","tipo": "serie"},
    {"nombre": "Lagarto Juancho","cancion": "lJnKtJnChLkLkOi.mp3","imagen": "lagarto_juancho.jpg","tipo": "dibujos"},
    {"nombre": "Las Chicas de Oro","cancion": "lChScSrPlKjHgFd.mp3","imagen": "las_chicas_de_oro.jpg","tipo": "serie"},
    {"nombre": "Las Tortugas Ninja","cancion": "lTtRtGsNnJkLkL.mp3","imagen": "las_tortugas_ninja.jpg","tipo": "dibujos"},
    {"nombre": "Los Fruitis","cancion": "lFrTtSkLkLkOiYu.mp3","imagen": "los_fruitis.jpg","tipo": "dibujos"},
    {"nombre": "Los Mundos de Yupi","cancion": "lMndSdYpLkLkOiYu.mp3","imagen": "los_mundos_de_yupi.jpg","tipo": "dibujos"},
    {"nombre": "El Coche Fantástico","cancion": "lCfFtStCcSvXnZ.mp3","imagen": "el_coche_fantastico.jpg","tipo": "serie"},
    {"nombre": "El Correcaminos","cancion": "lCrrCmSvXnZmWl.mp3","imagen": "el_correcaminos.jpg","tipo": "dibujos"},
    {"nombre": "Apartamento para Tres","cancion": "aPpRtMnTqWlKjHg.mp3","imagen": "apartamento_para_tres.jpg","tipo": "serie"},
    {"nombre": "El Cuentacuentos","cancion": "lCntCnTsLlSvXnZ.mp3","imagen": "el_cuentacuentos.jpg","tipo": "serie"},
    {"nombre": "La Pantera Rosa","cancion": "lPnTrRsLkLkOiYu.mp3","imagen": "la_pantera_rosa.jpg","tipo": "dibujos"},
    {"nombre": "Los Osos Amorosos","cancion": "lSrSmRsLvXnZmW.mp3","imagen": "los_osos_amorosos.jpg","tipo": "dibujos"},
    {"nombre": "La Casa de la Pradera","cancion": "lCsdLpRdLvXnZmW.mp3","imagen": "la_casa_de_la_pradera.jpg","tipo": "serie"},
    {"nombre": "Los Simpson","cancion": "lSmpSnLkLkOiYuTr.mp3","imagen": "los_simpson.jpg","tipo": "dibujos"},
    {"nombre": "Los Vigilantes de la Playa","cancion": "lVgLntSdPlYlKjH.mp3","imagen": "los_vigilantes_de_la_playa.jpg","tipo": "serie"},
    {"nombre": "MacGyver","cancion": "mGyVrLkLkOiYuTr.mp3","imagen": "macgyver.jpg","tipo": "serie"},
    {"nombre": "Marco","cancion": "mRcOlKjHgFdRtYx.mp3","imagen": "marco.jpg","tipo": "dibujos"},
    {"nombre": "Don Quijote de la Mancha","cancion": "dNqJtDlMnSvXnZ.mp3","imagen": "don_quijote_de_la_mancha.jpg","tipo": "dibujos"},
    {"nombre": "Noeli","cancion": "nElIkLkLkOiYuTr.mp3","imagen": "noeli.jpg","tipo": "dibujos"},
    {"nombre": "Pipi Calzaslargas","cancion": "pPcLsLrGsLkLkOiY.mp3","imagen": "pipi_calzaslargas.jpg","tipo": "dibujos"},
    {"nombre": "El Conde Duckula","cancion": "lCnDdClLvXnZmW.mp3","imagen": "el_conde_duckula.jpg","tipo": "dibujos"},
    {"nombre": "Blossom","cancion": "bLsSmGhJkLpOiY.mp3","imagen": "blossom.jpg","tipo": "serie"},
    {"nombre": "Power Rangers","cancion": "pWrRnGrSlKjHgFd.mp3","imagen": "power_rangers.jpg","tipo": "serie"},
    {"nombre": "Pumuki","cancion": "pMkLkLkOiYuTrSv.mp3","imagen": "pumuki.jpg","tipo": "dibujos"},
    {"nombre": "Salvados por la Campana","cancion": "sLvDdSpRlCmPnL.mp3","imagen": "salvados_por_la_campana.jpg","tipo": "serie"},
    {"nombre": "La Familia Monster","cancion": "lFmLmNtRlKjHgFd.mp3","imagen": "la_familia_monster.jpg","tipo": "serie"},
    {"nombre": "Con las Manos en la Masa","cancion": "cLsMnSnLmSvXnZ.mp3","imagen": "con_las_manos_en_la_masa.jpg","tipo": "serie"},
]

  